### PR TITLE
abort if there are no recipients

### PR DESCRIPTION
**Pull request by bmw2621**
Return out of on_message function if there are no raw_mentions in the message

### CODE REVIEW

**Comment by bmw2621** [comment]
standby, I thought __pycache__ was in gitignore

**Comment by bmw2621** [comment]
It is, I dont know why that commited

**Review by rbrady — CHANGES_REQUESTED** [review]
The file changed looks good.  For the other files, just remove them from the commit.

 git reset --soft HEAD~1
 git add main.py
 git commit --amend --no-edit

**Comment by bmw2621** [comment]
GGGAAAAHHHH

**Pull request closed without merging**
